title: <p align="center"> Punit Kumar Mohanty </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mohantypunit/">LinkedIn</a> |
  <a href="https://github.com/mohantypunit">GitHub</a>
  </p>
  
  <p align="justify">
  Iâ€™m an AI Consultant & AI-Platform Engineer / Solution Architect working at the intersection of <b>LLMs (RAG)</b>, <b>DevOps/MLOps</b>, <b>Azure/Kubernetes</b>, <b>Consulting</b> and <b>Training</b>.
  I build production-grade AI platforms and automation for tax, legal, audit, production and data teams. I have trained colleagues of different backgrounds on AI and also conducted workshops/hackathons. 
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-YH7L3LTHRL # Google Analytics tracking ID
